### PR TITLE
PL-31: Move search app site name configuration to configuration form.

### PR DESCRIPTION
**Pull request by mcarmichael21**
https://palantir.atlassian.net/browse/PL-31

## Description

Remove the alter hook, `search_api_federated_solr_form_search_api_federated_solr_search_app_settings_alter()` and add this logic to the rest of the search app configuration form.

This provides the option to search only on the current site by default. When there is a site_name field sent to the index, the search app configuration form will provide an option to pre-check the current site. If this is checked, the site visitor can still uncheck that option and see results from all sites.

## To Test

- Install a site and set up an index
- Edit the index and make sure there is **no** `site_name` field, example:  /admin/config/search/search-api/index/federated_search_index/fields
- Go to the search app configuration page, /admin/config/search-api-federated-solr/search-app/settings
- In the inspector, look at the value for the hidden `site_name_property` input field
- The value should be `true`
- There should be no `Set the "site name" facet to this site` option.

site_name_facet_option

- Go to the homepage
- Search for a term
- Confirm that the site name facet is not preselected

- Edit the index and **add** a `site_name` field
- Go to the search app configuration page
- In the inspector, look at the value for the hidden `site_name_property` input field
- The value should be blank
- There should be a `Set the "site name" facet to this site` option.
- Check this option

site_name_facet_option

- Go to the homepage
- Search for a term
- Confirm that the site name facet is preselected

### CODE REVIEW

**Review by froboy — CHANGES_REQUESTED** [review]
@mcarmichael21 I'm not seeing the right behavior...

- in demo site, ran `composer require palantirnet/search_api_federated_solr:dev-PL-31-Change-an-alter-call-to-a-callback-for-the-form`
- `phing build install`
- Confirm site name exists on index
- visited config page
- result `<input id="site-name-property" data-drupal-selector="edit-site-name-property" type="hidden" name="site_name_property">`
- Removed site name field on index, indexed, cleared caches (just to see if any change), still no change.

**Comment by damontgomery** [comment]
There are no more conflicts. I updated the code and testing steps.

**Comment by damontgomery** [comment]
Closing this for more end-to-end review.

**Comment by damontgomery** [comment]
I was able to do end-to-end testing and I updated the testing steps.

**Comment by jesconstantine** [comment]
I've incorporated this work into #77 and it appears to be working.  Closing this PR in favor of #77.  Thanks @mcarmichael21 and @damontgomery!

**Pull request closed without merging**
