### PR TITLE
add #39 to 7.x-2.x umhs-28: use canonical URL for results

### PR DESCRIPTION
**Pull request by byrond**
Add the canonical URL Search API index data alteration to the 2.x branch. (This was previously added to 7.x-1.x in #39.)

### CODE REVIEW

**Comment by byrond** [comment]
The index status for both indexes is `An error occurred while trying to determine the server index status. Please check the logs for details.` This status and the following message from the watchdog error log are also present on production:

```
May 28 14:10:29 web-18596 umich3[25028]: https://www.uofmhealth.org|1559052629|search_api|70.62.166.50|https://www.uofmhealth.org/admin/config/search/search_api/index/production_profiles|https://www.uofmhealth.org/admin/config/search/search_api|1||SearchApiException: An error occurred while trying to search with Solr: &amp;quot;500&amp;quot; Status: Server Error: Server Error{&amp;quot;error&amp;quot;:{&amp;quot;trace&amp;quot;:&amp;quot;java.lang.NullPointerException\n\tat org.apache.solr.search.QParser.getParser(QParser.java:314)\n\tat org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:161)\n\tat org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:267)\n\tat org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:156)\n\tat org.apache.solr.core.SolrCore.execute(SolrCore.java:2036)\n\tat org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:657)\n\tat org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:464)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:257)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:208)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)\n\tat org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:308)\n\tat org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:262)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1160)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1092)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)\n\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:518)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)\n\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)\n\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)\n\tat org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)\n\tat org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)\n\tat org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)\n\tat java.lang.Thread.run(Thread.java:745)\n&amp;quot;,&amp;quot;code&amp;quot;:500}} . in SearchApiSolrService->search() (line 1242 of /mnt/www/html/umich3/www/sites/all/modules/search_api_solr/includes/service.inc). request_id="v-5912cdf8-8152-11e9-8225-67984a2cdcda"
```

**Comment by agentrickard** [comment]
Following. This would require a new release.

**Review by jesconstantine — APPROVED** [review]
Reviewed and tested with Byron - LGTM 🌮

**Comment by agentrickard** [comment]
Did you push this to the Drupal origin, too?

**Comment by jesconstantine** [comment]
@agentrickard all I did was merge I didn't push anything. I think Byron was going to touch base with you re: releasing

**Pull request merged**
